### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by psimm** [qagentur/texttunnel#1]
- [x] Add CI with Github Action and pytest
- [x] Implement cost estimation
- [x] Implement logging (implemented in processor.py)
- [x] Add example script/notebook (@phuoviala), see also the example added in #3 
- [x] Let processor take in an object from memory of the class ChatCompletionRequest (#3)
- [x] Implement binpacking input texts (contained in #6)
- [x] Implement input validation (#4)
- [x] Implement caching (#6)
- [x] Make token counting more intuitive and binpacking less likely to cause exceeding the context size (#14)
- [x] Create documentation with Sphinx and publish it on Github page
- [x] Remove warning from readme
- [x] Release to PyPi
- [ ] Improve validation for function definition
- [ ] Add tests for processor.py using mocked API response
- [ ] Announce on social media (Twitter, LinkedIn, Hacker News)

**Comment by phuoviala** [comment]
@psimm Is the add example script done?

**Comment by psimm** [comment]
Yes, the sentiment analysis example is done. We could add more examples later. Given the timelines of other projects, I wouldn't prioritize it right now

**Comment by psimm** [comment]
I moved the remaining to dos into issues. Closing.
